export default {
	trainingTitle: `Personal training and follow-up`,
	trainingTitleText:`FUTURE provides all its clients with personal training and a monitoring service for patients so that they continue to enjoy a high quality of life with dental implants and during the rehabilitation process. By providing specifically-tailored personal training and comprehensive follow-up support, it's possible to continually improve each dentist's proficiency in implantation and rehabilitation, helping each to become a leading professional in this particular field. Throughout the training and follow-up, it's necessary to exercise skills so each dentist can optimize and integrate FUTURE products into client treatments and rehabilitation programs. Familiarity with the company's products gained during training allows the dentist to match the best individual treatment to the highest quality of service and product for patients`,
	trainingTitlePartOne:`Our service includes`,
	trainingTitlePartOneBulletPointOne:`Training at the dentist's own clinic – FUTURE can guide the dentist at their own clinic, on the day and time most convenient for them. The training is comprehensive and given by a special team from the company, which arrives at the clinic with the relevant equipment about in which the dentist has an interest, and provides the most comprehensive information to help the client gain proficiency and professionalism during the performance of all procedures`,
	trainingTitlePartOneBulletPointTwo:`Visiting FUTURE – to gain an appreciation of the professionalism of the company, all clients are invited to witness all rehabilitation steps at our advanced facility. An experienced guide will provide comprehensive training on every product implantation subject`,
	trainingTitlePartOneBulletPointThree:`24 hour-a-day support – FUTURE staff are available 24 hours-a-day to take calls concerning any question, assistance or help required`,
	trainingTitlePartOneText:` `,
	trainingTitlePartTwo:`Personal attention and follow-up, throughout the process`,
	trainingTitlePartTwoText:`FUTURE’s clients are not treated as items of random, one-off business. Many clients stay with us throughout the years, as we provide professional, up-to-the-minute data on new product ranges and innovations beyond the initial contact period and first selection of product. Once a dentist becomes a FUTURE client, he or she receives consistent and continual training material, written by leading professionals. FUTURE believes that personal attention and accessibility are very important factors that dentists take into account when making choices about partner companies: it's vital therefore, that FUTURE provides round-the-clock support systems that can handle any query or provide solutions to all situations`,
	trainingTitlePartThree:`Our clients are our assets`,
	trainingTitlePartThreeText:`Over and above the comprehensive service package we offer to clients, FUTURE knows that what's important to dentists is the assurance that the information and advice provided is the most up-to-date and professional available, complies and exceeds all contemporary standards and is in accordance with the most recent research data. To ensure that all employees keep abreast of the most recent advances and that the product range remains future-proof, our staff attend professional refresher courses, seminars and training courses on a regular basis. Knowledge is continually updated therefore, and is founded on ongoing research and advances in the field. To be worthy of the continued support of our marketplace, FUTURE is meticulous about developing technology and new research. When dentists choose to partner FUTURE, they choose to join a welcoming, professional body that never leaves its clients on their own in the treatment and rehabilitation process. FUTURE makes sure that it stays with its clients ‘for the duration`,
};