import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useRouter } from 'next/router';
import en from '../languages/en';
import ka from '../languages/ka';
import CardsComponent from '../components/CardsComponent';
import CarouselComponent from '../components/CarouselComponent';

export default function Home () {
	const {
		locale,
	} = useRouter();
	const language = locale === 'en' ? en : ka;

	return (
		 <div className={styles.container}>
			 <Head>
				 <title>Future Implants</title>
				 <meta
						name="description"
						content="Generated by create next app" />
				 <link
						rel="icon"
						href="/favicon.ico" />
			 </Head>
			 <CarouselComponent/>
			 <CardsComponent />
		 </div>
	);
}
